steps:
- name: 'gcr.io/cloud-builders/gradle'
  args: ['build']
  
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/$_IMAGE_NAME:$BUILD_ID', '.']
  dir: 'parking-service/$_SERVICE_NAME'

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/$_IMAGE_NAME:$BUILD_ID']
- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - set
  - image
  - deployment
  - $_DEPLOYMENT_NAME
  - $_CONTAINER=gcr.io/$PROJECT_ID/$_IMAGE_NAME:$BUILD_ID
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=$_COMPUTE_ZONE'
  - 'CLOUDSDK_CONTAINER_CLUSTER=$_CLUSTER'
